name: Go Release
on:
  push:
    tags:
      - 'v*'
  # 添加手动触发
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: true
        default: 'v0.0.0'
      
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          git tag ${{ github.event.inputs.version }}
          
      - name: Install upx
        run: sudo apt-get install -y upx
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 'latest'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
